### ISSUE TITLE
ES 2.0 readiness and default http behavior changes

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#230]
Elasticsearch master is now close to being ES 2.0 beta. While we wait for this beta release, discussing Logstash compatibility with 2.0 here. This also has implications on our [plans](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/150) of splitting current plugin into 2 separate ones: http only and native plugin (node and transport)

- [x] `http` protocol works with ES 2.0. All tests are passing
- [ ] Transport and Node: Currently this plugin bundles 1.7 jars. Connecting to ES 2.0 [breaks](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/226#issuecomment-132385211). Since ES 2.0 is a major version, changes are not forward or backward compatible with respect to java clients. **Action:** This plugin should not be updated with 2.0 jars because the future is *only* http for this plugin. 
- [ ] Release first version of the [native](https://github.com/logstash-plugins/logstash-output-elasticsearch_native) plugin bundled with 2.0 jars. This plugin *only* has `transport` and `node` client functionality. **Timeline**: Release a 2.0.beta in sync with ES 2.0 beta. Release another version as soon as ES 2.0 is released. @talevy [PR](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/226) which make this plugin compatible with 2.0 needs to go into native plugin
- [ ] Shield functionality: Today, users need to install `logstash-output-elasticsearch-shield` to bring in security features to `transport`. We need to release 2.0.beta1 which is compatible with Shield 2.0.beta1 and 2.0 GA shield plugin in sync with Shield 2.0.
- [ ] Remove all node and transport protocol code from this plugin. All future native development will happen in es-native plugin. No PRs touching `node` and `transport` code will be merged here, so no backports.
- [ ] Add warnings when `protocol` is set to `node` or `transport` during runtime and notify user of how to install new native plugin
- [ ] For Logstash version 1.6, this plugin will become only http, so it will be ES 2.0 ready out of the box.
- [ ] Change documentation to reflect these developments. Mention that current 1.5.x will not be compatible with ES 2.0 for `transport` and `node` protocol. Provide workarounds to install native plugin on top of LS 1.5.x.

**Comment by andrewvc** [comment]
I think we should make the 'native' plugin a straight fork of the mainline version (with ES2.0 jars) to reduce time maintaining backports. We can rip out the HTTP stuff again when we make the true split for LS2.0.

**Comment by andrewvc** [comment]
Maybe we could just remove 'http' from the validation for protocol in that version.

**Comment by suyograo** [comment]
Closing this in favor of the new plan in https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/237
