### ISSUE TITLE
Updated: ES 2.0 readiness and default http behavior changes

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#237]
Follow up of #230 with our current thinking after a discussion with the team. As per previous plan (#230), if we default to http in 1.6, it will break existing configs. We are going to release Logstash 2.0 to track Elasticsearch 2.0 to adhere to semantic versioning. Also, switching to http will provide a clean first user experience for anyone downloading Elasticsearch 2.0 and using LS with it.

Additional rationale for changing default to http: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/150

The sequence of steps for these changes:

- [x] Remove node and protocol code from this plugin #216 
- [x] Add sniffing to the HTTP protocol #182 
- [x] Reduce default bulk size to 500 #181 
- [x] Delegate to elasticsearch-ruby client for connection logic #236 
- [x] Only support `http` protocol for this plugin. No more 'protocol' option
- [x] Rename 'host' option to 'hosts'
- [x] Release a 2.0 beta version of this plugin to track ES 2.0 beta1
- [x] Rename logstash-output-elasticsearch-native to logstash-output-elasticsearch-java
- [x] Release v1.0 of logstash-output-elasticsearch_java with ES 1.7 jars
- [x] Release v2.0 of logstash-output-elasticsearch_java with ES 2.0 jars
- [x] Release v2.0 of logstash-output-elasticsearch-shield with Shield 2.0.beta1 and compatible on LS 2.0.beta1
- [x] Introduce documentation for native
- [x] Delete legacy elasticsearch_http input
- [x] Publish documentation for 2.0 of this plugin.
- [x] Bundle LS core release with only logstash-output-elasticsearch
- [x] Blog about performance and feature parity with java client.

**Comment by jordansissel** [comment]
+1 this plan.

**Comment by andrewvc** [comment]
@suyograo when can we delete `logstash_http`?
