### ISSUE TITLE
[Doc][Meta] Improvements to output-elasticsearch docs

### ISSUE THREAD

**Issue by karenzone** [logstash-plugins/logstash-output-elasticsearch#885]
Improvements to documentation
- [x] Add note about `_type` change from `doc` to `_doc` #884 
- [x] Request for "more explicit documentation for both upsert and doc_as_upsert" in #928
- [x] Fix index default value #927

**Comment by karenzone** [comment]
Continued in #978
